version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.1.1
    steps:
      - checkout
      - run:
          name: Validate AMI
          command: |
            ls -al
            packer validate -var-file=./vars.json ami.json
  build:
    docker:
      - image: hashicorp/packer:1.1.1
    steps:
      - checkout
      - run:
          name: Validate AMI
          command: |
            ls -al
            packer build -var-file=./vars.json ami.json

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-base:
          requires:
            - validate
      - build-snowflake:
          requires:
            - validate
            - build-base
      - canary-snowflake:
          requires:
            - build-snowflake