version: 2
jobs:
  build:
    filters:
      branches:
        only:
          - master
    docker:
      - image: hashicorp/packer:1.1.1
    steps:
      - checkout
      - run:
          name: Validate AMI
          command: |
            packer build \
            -var "aws_region=us-east-1" \
            -var "aws_access_key=${AWS_ACCESS_KEY_ID}" \
            -var "aws_secret_key=${AWS_SECRET_ACCESS_KEY}" \
            -var 'source_ami=ami-07ebfd5b3428b6f4d' \
            ami.json

workflows:
  version: 2
  build-deploy-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master